name: online_radio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  just_audio: ^0.1.3
  loading: ^1.0.2
  equatable: ^1.1.1
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  cached_network_image: ^2.0.0
  flutter_svg: ^0.18.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/